name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Packages Docker Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - name: Prepare
        id: prep
        shell: bash
        run: |
          GHCR_IMAGE=ghcr.io/${{ github.repository_owner }}/eosio
          VERSION=latest
          COMPLETE_IMAGE_NAME="${GHCR_IMAGE}:${VERSION}"
          echo "::set-output name=tags::${COMPLETE_IMAGE_NAME}"

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          tags: ${{ steps.prep.outputs.tags }}
          push: true
          secrets: |
            GIT_AUTH_TOKEN=${{ github.token }}

      - name: Deploy with CapRover CLI
        run: npx caprover deploy
        env:
          CAPROVER_URL: ${{ secrets.CAPROVER_URL }}
          CAPROVER_PASSWORD: ${{ secrets.CAPROVER_PASSWORD }}
          CAPROVER_APP: ${{ secrets.CAPROVER_APP }}
          CAPROVER_IMAGE_NAME: ${{ steps.prep.outputs.tags }}
